config/routes.rb
Wardround::Application.routes.draw do
  
 
  
  
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  

  root :to => "rounds#index"
  
  resources :claims
  
  resources :reports

  resources :rounds do
      member do
        get 'return'
      end
    end

  resources :visits do
      collection do
        post 'remove'
        post 'charge'
        post 'uncharge'
      end
    end

  resources :patients  do
      member do
        post 'discharge'
        post 'undischarge'
        post 'decrement'
        post 'changeward'
        post 'changestatus'
        post 'under'
        post 'transfer'
        get 'report'
      end
    end
  
  resources :hospitals do
    collection do
      get 'wards_by_hospital'

    end
    member do
      get 'report'
      get 'handover'
      get 'change_hospital'
    end
  end
  
  resources :wards
  

end

app/models/visit.rb
class Visit < ActiveRecord::Base
 
  belongs_to :doctor
  belongs_to :ward
  belongs_to :patient
  
  def self.code(patient,theDate)
    # code is blank if no visits, 0 if visited but no charge, 1 if one visit, 2 if 2 on same day, etc
    @visits=Visit.where(["patient_id=? and date=?",patient,theDate.strftime('%Y-%m-%d')])
    code=" "

    if @visits.count>0
      chargeCount=0;
      @visits.each do |visit|
        if visit.item!="0"
          chargeCount=chargeCount+1
        end
      end
      code=chargeCount.to_s
    end
    return code




  end
  
  def item_text
      r="---"
      r="No Charge" if self.item=="0"
      r="Normal" if self.item=="1"
      r="Long" if self.item=="2"
      return r
    
  end

  def doctor
      if self.doctor_id
        doctor=User.find(self.doctor_id)
        return doctor.name
      end
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  def index
    @patients=Patient.joins(:visits).where("visits.billed = 'f' or visits.billed IS NULL").where("visits.item>0").order(:admission).distinct
    request.format="mobile"
    respond_to do |format|
      format.js
      format.mobile
      format.html # index.html.erb
      format.json { render :json => @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])




    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new

    @visit = Visit.new

    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @visit }
      format.js
      format.mobile {render :nothing => true}
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    # this is called from Ajax

    @visit = Visit.new
    @patient=Patient.find(params[:patient_id])
    @round=Round.find(params[:round_id])
    @visit.doctor_id=current_user.id
    @visit.patient_id=@patient.id
    @visit.date=@round.date
    @visit.round_id=@round.id
    @visit.duration=@round.hospital.duration
    @visit.item=@round.hospital.item
    
    if @patient.charge == NIL or @patient.charge==0
      @visit.item='0'
    end
    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, :notice => 'Visit was successfully created.' }
        format.json { render :json => @visit, :status => :created, :location => @visit }
        format.js 
      else
        format.html { render :action => "new" }
        format.json { render :json => @visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])
    @billFlag=0
    @billFlag=1 if params[:visit][:billed].present?
    @patient=@visit.patient
    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, :notice => 'Visit was successfully updated.' }
        format.json { respond_with_bip(@visit) }
        format.js
      else
        format.html { render :action => "edit" }
        format.json { render :json => @visit.errors, :status => :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
  

  def remove
    @visit = Visit.where('patient_id=? and round_id=?',params[:patient_id],params[:round_id]).first
    @visit.destroy
    @patient_id=params[:patient_id]
    @patient=Patient.find(params[:patient_id])
    @round_id=params[:round_id]
    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
      format.js 
      format.mobile {render :nothing => true}
    end
  end
  
  def charge
    @visit = Visit.where('patient_id=? and round_id=?',params[:patient_id],params[:round_id]).first
    item=1;
    if params[:item]
        item=params[:item]
    end
    if @visit
      @visit.item=item

      @visit.update_attribute(:item,@visit.item)
    else
        @visit = Visit.new
        @patient=Patient.find(params[:patient_id])
        @round=Round.find(params[:round_id])

        @visit.patient_id=@patient.id
        @visit.date=@round.date
        @visit.round_id=@round.id
        @visit.duration=@round.hospital.duration
        @visit.item=item
        @visit.save    
    end
    
    respond_to do |format|
      format.html
      format.js {render :nothing => true}
    end
  end
  def uncharge
    @visit = Visit.where('patient_id=? and round_id=?',params[:patient_id],params[:round_id]).first
    if @visit
      @visit.item="0"

      @visit.update_attribute(:item,@visit.item)
    end
    respond_to do |format|
      format.html
      format.js {render :nothing => true}
    end
  end
  private
      # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:date, :doctor_id, :duration, :item, :chargenote, :patient_id, :ward_id, :billed)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_chargenote.html.erb
<%= best_in_place @visit, :chargenote, :type => :input,:ok_button => 'Save',:place_holder => '---Add',:cancel_button => 'Cancel' %>
And this stuff too

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :patient_id %><br />
    <%= f.number_field :patient_id %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br />
    <%= f.number_field :doctor_id %>
  </div>
  <div class="field">
    <%= f.label :ward_id %><br />
    <%= f.number_field :ward_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/create.js.erb
$('#chargenoteplace').html("<%=j best_in_place @visit, :chargenote, :type => :input,:ok_button => 'Save',:place_holder => '---Add',:cancel_button => 'Cancel' %>")
$('#chargeicon-<%=@patient.id%>').html("<%=j @patient.icons(@round.id) %>");
$('.best_in_place').best_in_place();

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <tr>
    <th>Patient</th>
    <th>Doctor</th>
    <th>Ward</th>
    <th>Date</th>
    <th>Duration</th>
    <th>Item</th>
    <th>Notes</th>
		<th>Claim</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
    <td><%= visit.patient_id %></td>
    <td><%= visit.doctor_id %></td>
    <td><%= visit.ward_id %></td>
    <td><%= visit.date %></td>
    <td><%= visit.duration %></td>
    <td><%= visit.item %></td>
    <td><%= visit.notes %></td>
    <td><%= visit.claim_id %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/index.mobile.erb
<div data-role="page" data-theme="b" id='visitreport'  > 
     <div data-role="header">
     <%= link_to 'Back', :back,'data-transition'=>'slide','data-icon'=>'back','data-direction'=>'reverse' %>
     		<%=link_to 'Home',rounds_path, 'data-transition'=> 'slide','data-icon'=>"home","data-iconpos"=>"notext",'data-direction'=>'reverse'%>
     		
					<h1>Unbilled Patient Report</h1>
     </div>
<div data-role="content">
	<div data-role="fieldcontain">

<style>
#tablereport {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    
    border-collapse: collapse;
}

#tablereport td, #tablereport th {
    font-size: 1em;
    border: 1px solid #000000;
    padding: 3px 7px 2px 7px;
}

#tablereport th {
    font-size: 1.1em;
    text-align: left;
    padding-top: 5px;
    padding-bottom: 4px;
    background-color: #5e87b0;
    color: #ffffff;
}

#tablereport tr.alt td {
    color: #000000;
    background-color: #EAF2D3;
}
</style>

<table data-role="table" id="tablereport">

<thead>
<th>Patient</th>
<th>Hospital</th>
<th>Admission</th>
<th>Discharge</th>
<th>Status</th>
<th>Visits</th>
<th>Charged</th>
<th>Billed</th>
</thead>




<tbody>
<% @patients.each do |patient| %>
<tr>
<td><%= link_to patient.name,report_patient_path(patient,:return=>:unbilled) %></td>
<td><%= patient.ward.hospital.name %></td>
<td><%= patient.admission%></td>    
<td><%= patient.discharge %></td>
<td><%= patient.status %></td>
<td><%= patient.visitsTotal %></td>
<td><%= patient.visitsCharged %></td>
<td><%= patient.visitsBilled %></td>
</tr>
<% end %>
</tbody>
</table>

</div>
</div>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/remove.js.erb
$('#chargeicon-<%=@patient_id%>').html("<%=j @patient.icons(@round_id) %>");

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

Visit to <%= @visit.patient.name %> on <%=@visit.date%><p>

<p>
  <b>Ward:</b>
	<%= best_in_place @visit.patient, :ward_id, :type => :select, :collection => @visit.patient.ward.hospital.wards.map {|x| [x.id, x.name] } %>
</p>

<p>
	<b>Duration:</b>
  <%= best_in_place @visit, :duration, :type => :input %> 	 
</p>
<p>
	<b>Reason:</b>
  <%= best_in_place @visit.patient, :reason, :type => :input,:ok_button => 'Save', :cancel_button => 'Cancel' %> 	 
</p>
<p>
	<b>Note:</b>
  <%= best_in_place @visit.patient, :note, :type => :textarea,:ok_button => 'Save', :cancel_button => 'Cancel' %> 	 
</p>

<%= link_to 'Discharge', discharge_patient_path(patient,:round_id=>@visit.id),:method=>:post,:remote=>true %>
<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>

app/views/visits/update.js.erb
<% if @billFlag==1 %>
	$('#billed-<%=@patient.id.to_s%>').html("<%=j @patient.visitsBilled.to_s %>");
<% end %>