config/routes.rb
Wardround::Application.routes.draw do
  
 
  
  
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  

  root :to => "rounds#index"
  
  resources :claims
  
  resources :reports

  resources :rounds do
      member do
        get 'return'
      end
    end

  resources :visits do
      collection do
        post 'remove'
        post 'charge'
        post 'uncharge'
      end
    end

  resources :patients  do
      member do
        post 'discharge'
        post 'undischarge'
        post 'decrement'
        post 'changeward'
        post 'changestatus'
        post 'under'
        post 'transfer'
        get 'report'
      end
    end
  
  resources :hospitals do
    collection do
      get 'wards_by_hospital'

    end
    member do
      get 'report'
      get 'handover'
      get 'change_hospital'
    end
  end
  
  resources :wards
  

end

app/models/round.rb
class Round < ActiveRecord::Base
  has_many :claims
  belongs_to :hospital
  # round is a date and number - in case mpre than one ward round is done per day
  
  # Gets latest round for today, or creates new round if doesn/t exist
  def self.today(doctor)
    @round=Round.where('date=? and doctor_id=?',Date.today,doctor).order("created_at DESC")[0]
    if @round.blank?
      @round=Round.new
      @round.date=Date.today
      @round.number=1
      @round.start=Time.now
      @round.save
    end
    return @round
  end
  
  def inpatients
     @patients = Patient.joins(:ward => :hospital).where("hospital_id=?",self.hospital_id).where(["admission <=? and (discharge is NULL or discharge>=?)",self.date,self.date]).order("ward_id ASC")
     #@patients = Patient.joins(:ward => :hospital).where("hospital_id=?",self.hospital_id).where(["admission <=? and (discharge is NULL or discharge>=?)",self.date,self.date],:order=>"ward_id ASC")

  end
  
  
  def self.ondate(date,order="DESC",hospital,doctor)
      @round=Round.where('date=? AND hospital_id=? and doctor_id=?',date,hospital,doctor).order("created_at "+order)[0]
      if @round.blank?
        @round=Round.new 
        @round.date=date
        @round.number=1
        if hospital
          @round.hospital_id=hospital
        elsif Hospital.count==1
          @round.hospital_id=Hospital.first.id
        end
        @round.doctor_id=doctor
        @round.save
      end

      return @round
      
    end  
  
  
  def previous(doctor)
      round=0
      if self.number>1
        @round=Round.where('date=? and number=? and hospital_id=? and doctor_id=?',self.date,self.number-1,self.hospital_id,doctor)[0]
        round=@round.id
      end
      return round
  end
  
  def visits(doctor)
      Round.where('date=? AND hospital_id=? AND doctor_id=?',self.date,self.hospital_id,doctor).count
  end
  
  def next(doctor)
      round=0

      if self.visits(doctor)>self.number
        @round=Round.where('date=? and number=? and doctor_id=?',self.date,self.number+1,doctor)[0]
        if @round 
          round=@round.id
        end
      end
      return round
  end

  def return
      @round=Round.new
      @round.hospital_id=self.hospital_id
      @round.date=self.date
      @round.number=self.visits(self.doctor_id)+1
      @round.start=Time.now
      @round.doctor_id=self.doctor_id
      @round.save
      return @round
  end    
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  # GET /rounds
  # GET /rounds.json
  

  def index
    if params[:id] and params[:id]!='0'
      @round=Round.find(params[:id])
    elsif params[:round_id] and params[:round_id]!='0'
      @round=Round.find(params[:round_id])
    elsif Hospital.count==1 or params[:hospital_id]
        date=Date.today
        date=Date.strptime(params[:date],"%d/%m/%y") if params[:date]
        order="DESC"
        order = params[:order] if params[:order]
        @round=Round.ondate(date,order,params[:hospital_id],current_user.id)
    end
    if @round
        redirect_to :action => "show", :id => @round.id
        return
    end
    @hospitals=Hospital.all
    #@claims=Array.new
    #@hospitals.each do |hospital|
      #@claims[hospital.id]=Claim.find_or_create_by_round_id_and_hospital_id(:round_id=>@round.id,:hospital_id=> hospital.id)
    #end
    if request.xhr?
      request.format = "mobile"
    end
    respond_to do |format|
      format.html
      format.mobile
      format.json { render :json => @patients }
    end
    

   
    

  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    if params[:id] and params[:id]!='0'
      @round=Round.find(params[:id])
    elsif params[:round_id] and params[:round_id]!='0'
      @round=Round.find(params[:round_id])
    else
        date=Date.today
        date=Date.strptime(params[:date],"%d/%m/%y") if params[:date]
        order="DESC"
        order = params[:order] if params[:order]
        @round=Round.ondate(date,order)
    end

    @patients = @round.inpatients
    #@patients=Patient.find(:all)
    @hospitals=Hospital.all
    @wards=Array.new
    @hospitals.each do |hospital|
      @wards[hospital.id]=Ward.where('hospital_id=?',hospital.id)
    end
    @hospital=Hospital.all
    if request.xhr?
      request.format = "mobile"
    end

    respond_to do |format|

      format.html # index.html.erb
      format.mobile
      format.json { render :json => @patients }
    end
 

  end

  # GET /rounds/new
  # GET /rounds/new.json
  def new
    @round = Round.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @round }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
  end


  
  

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(params[:round])
    @round.doctor_id=current_user.id
    respond_to do |format|
      if @round.save
        format.html { redirect_to @round, :notice => 'Round was successfully created.' }
        format.json { render :json => @round, :status => :created, :location => @round }
      else
        format.html { render :action => "new" }
        format.json { render :json => @round.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.json
  def update
    @round = Round.find(params[:id])

    respond_to do |format|
      if @round.update_attributes(params[:round])
        format.html { redirect_to @round, :notice => 'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @round.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round = Round.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end
  
  def return
     @round = Round.find(params[:id])
     @round = @round.return

     redirect_to :controller=>:rounds,:action=>:show,:id=>@round.id

  end
  private
      # Use callbacks to share common setup or constraints between actions.
    def set_round
      @round = Round.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def round_params
      params.require(:round).permit(:claimable, :date, :doctor_id, :duration, :finish, :hospital_id, :start)
    end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :doctor_id %><br />
    <%= f.number_field :doctor_id %>
  </div>
  <div class="field">
    <%= f.label :hospital_id %><br />
    <%= f.number_field :hospital_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= best_in_place :duration %>
  </div>
  <div class="field">
    <%= f.label :claimable %><br />
    <%= f.number_field :claimable %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :finish %><br />
    <%= f.datetime_select :finish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
Round at:<p>

<% @hospitals.each do |hospital| %>
<%= link_to hospital.name,rounds_path(:hospital_id=>hospital.id) %><br>
<% end %>

or 

<%= link_to "Report", hospitals_path%>

app/views/rounds/index.mobile.erb
<div data-role="page" data-theme="b" style='max-width: 600px;'> 
     <div data-role="header">
           <h1>Ward Round</h1> 
     </div> 
     <div data-role="content">     
           <ul data-role="listview" data-inset="true" data-dividertheme="a"> 
                 <li data-role="list-divider">Hospitals</li> 
								<% @hospitals.each do |hospital| %>
								<li><%= link_to hospital.name,rounds_path(:hospital_id=>hospital.id), "data-transition"=> "slide" %><span class="ui-li-count"><%= hospital.inpatients.count %></span></li>
								<% end %>
           </ul>   

<%= link_to "Admit New Patient",new_patient_path,"data-role"=>"button","data-theme"=>"b",'data-transition'=>'slide' %> 
<%= link_to "Report", hospitals_path,"data-role"=>"button","data-theme"=>"b",'data-transition'=>'slide'%>   
<%= link_to "Handover", hospitals_path(:handover=>true),"data-role"=>"button","data-theme"=>"b",'data-transition'=>'slide'%> 
<%= link_to "Billing Summary", visits_path,"data-role"=>"button","data-theme"=>"b",'data-transition'=>'slide'%>  
     </div>   

<%= render partial: "shared/footer" %>
</div>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/show.html.erb
<h1><%= @round.hospital.name%> <%=@round.date %> <%= @round.number.ordinalize+' visit' %> (<%= @round.id %>)</h1>
<%= link_to 'New visit on same day', return_round_path(@round) %><p>
<%= link_to 'Previous', rounds_path(:date=>@round.date-1.day,:round_id=>@round.previous,:hospital_id=>@round.hospital_id) %>
Number -----<%= @round.number%>
Hospital -----<%= @round.hospital_id%>
Date -----<%= @round.date%>
Number-----<%= @round.number%>
Visits -----<%= @round.visits%>



	<% if @round.hospital.showtime %>
								<a href="#" onclick="$('#claim-<%=@round.hospital.id%>').toggle('slow');return false;" style="text-decoration: none">Time</a>
								<% end %>
								<%= render :partial => "claim", :object => @claims[patient.ward.hospital.id] if @round.hospital.showtime%>


<% @patients.each do |patient| %>
<table>
  <tr>
		<td>

			<%= check_box_tag @round.id,patient.id,patient.visited?(@round.id),:class => 'patient-visit' %>

			</td>
    <td>
	<span <%= "style='font-weight: bold'" if patient.under==1%>><%= link_to patient.name,patient_path(patient,:round_id=>@round.id) %> </span></td>
    <td>
	<%= collection_select("ward",:id, @wards[@round.hospital_id], :id, :name, {:selected => patient.ward.id}, {:class=>'ward-select',:name=>patient.id}) %>
	</td>

    <td><%= patient.admission %></td>
    <td id='discharge-<%=patient.id %>'><%= patient.discharge %></td>
		<td id='discharge-command-<%=patient.id %>'>
		<% if patient.discharge %>
		<%= link_to 'Decrement', decrement_patient_path(patient),:method=>:post,:remote=>true %>
		<% else %>
		<%= link_to 'Discharge', discharge_patient_path(patient,:round_id=>@round.id),:method=>:post,:remote=>true %>
		<% end %>
		</td>

  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Patient', new_patient_path(:hospital_id=>@round.hospital_id) %>
<%= link_to 'Show All Hospital', rounds_path if Hospital.count>1 %>

app/views/rounds/show.mobile.erb
<div data-role="page" data-theme="b" id='showround'  > 
     <div data-role="header">
				<%=link_to 'Home',rounds_path, 'data-transition'=> 'slide','data-icon'=>"home","data-iconpos"=>"notext",'data-direction'=>'reverse'%>
				<%=link_to 'Report',hospitals_path(:theDate=>@round.date),'data-transition'=>'slide'%>
           <h1><%= @round.hospital.name%></h1>

     </div> 
     <div data-role="content">
			<div style="text-align:center">
				<div data-role="controlgroup" data-type="horizontal">
				<%= link_to 'Previous', rounds_path(:date=>@round.date-1.day,:round_id=>@round.previous(current_user.id),:hospital_id=>@round.hospital_id),'data-role'=>'button','data-icon'=>"arrow-l", 'data-iconpos'=>"notext",'data-mini'=>"true",'data-transition'=>'slide','data-direction'=>'reverse'%>
				<button data-mini='true'><%= @round.date %> (<%= @round.number.ordinalize%>)</button>

				
					<a href="#popupDialog" data-rel="popup" data-position-to="window" data-role="button" data-mini="true" data-icon='plus' data-iconpos='notext' data-transition="pop">Dialog</a>
					

<%= link_to 'Next', rounds_path(:date=>@round.date+1.day,:round_id=>@round.next(current_user.id),:order=>'ASC',:hospital_id=>@round.hospital_id),'data-role'=>'button','data-iconpos'=>"notext",'data-icon'=>"arrow-r",'data-mini'=>"true",'data-transition'=>'slide' unless @round.date==Date.today and @round.number==@round.visits(current_user.id)%>
</div>
			</div>
			<div data-role="popup" id="popupDialog" data-overlay-theme="a" data-theme="c" style="max-width:400px;" class="ui-corner-all">
				<div data-role="header" data-theme="b"
<
< class="ui-corner-top">
					<h1>Return visit on same day?</h1>
				</div>
				<div data-role="content" data-theme="d" class="ui-corner-bottom ui-content">
					<h3 class="ui-title">Are you sure you want add another visit on this day?</h3>
					 <%= link_to "Cancel", round_path(@round),'data-role'=>'button','data-icon'=>'plus','data-inline'=>"true",'data-theme'=>'b','data-mini'=>'true' %>  
					<%= link_to "Revisit", return_round_path(@round),'data-role'=>'button','data-icon'=>'plus','data-inline'=>"true",'data-theme'=>'b','data-mini'=>'true' %>
					 
				</div>
			</div>
		 <ul data-role="listview" data-inset="true" data-dividertheme="b"> 
		  <% current_ward="" %>
			<% @patients.each do |patient| %>
			 <% if patient.ward.id != current_ward %>
			 <li data-role="list-divider"><%= patient.ward.name %></li>
			 <% current_ward=patient.ward.id %>
			<% end %>
			<li>
				<div class='checkBoxLeft'><%= check_box_tag @round.id,patient.id,patient.visited?(@round.id),:class => 'hidden-checkbox'%></div><%= link_to raw(patient.name+ " <span id='chargeicon-"+patient.id.to_s+"'>"+patient.icons(@round.id)+"</span>"),patient_path(patient,:round_id=>@round.id,:flag=>1),:class=>"detailListText","data-transition"=>"slide",'data-icon'=>"bars"%></li>
			<% end %>
		</ul>
<%= link_to "Admit New Patient",new_patient_path("hospital_id"=>@round.hospital.id,"round_id"=>@round.id),"data-role"=>"button","data-theme"=>"b",'data-transition'=>'slide' %> 
			

     
     </div>   
    <div data-role="footer" data-position="fixed">
     <h4>WardRoundApp by LemLink</h4>
    </div> 
</div>

app/views/rounds/show_all.html.erb
<h1><%=@round.date %> <%= @round.number.ordinalize+' visit' %> (<%= @round.id %>)</h1>
<%= link_to 'New visit on same day', return_round_path(@round) %><p>
<%= link_to 'Previous', rounds_path(:date=>@round.date-1.day,:round_id=>@round.previous,:hospital_id=>@round.hospital_id) %>

<%= link_to 'Next', rounds_path(:date=>@round.date+1.day,:round_id=>@round.next,:order=>'ASC',:hospital_id=>@round.hospital_id) unless @round.date==Date.today and @round.number==@round.visits%><p>

<table>

<% current_hospital=0 %>
<% @patients.each do |patient| %>

	<% if patient.ward.hospital.id!=current_hospital%>
	<tr><td colspan=2 valigh='top'><b><%= patient.ward.hospital.name%></b></td>
<td valign='middle'>
	<% if patient.ward.hospital.showtime %>
								<a href="#" onclick="$('#claim-<%=patient.ward.hospital.id%>').toggle('slow');return false;" style="text-decoration: none">Time</a>
								<% end %>
								</td>
	<td colspan=5>
			<%= render :partial => "claim", :object => @claims[patient.ward.hospital.id] if patient.ward.hospital.showtime%>
			</td>
			
		</tr>
	<% end%>
	<% current_hospital=patient.ward.hospital.id%>
  <tr>
		<td>

			<%= check_box_tag @claims[patient.ward.hospital.id].id,patient.id,patient.visited?(@claims[patient.ward.hospital.id].id),:class => 'patient-visit' %>

			</td>
    <td>
	<span <%= "style='font-weight: bold'" if patient.under==1%>><%= link_to patient.name,patient_path(patient,:round_id=>@round.id) %> </span></td>
    <td>
	<%= collection_select("ward",:id, @wards[current_hospital], :id, :name, {:selected => patient.ward.id}, {:class=>'ward-select',:name=>patient.id}) %>
	</td>

    <td><%= patient.admission %></td>
    <td id='discharge-<%=patient.id %>'><%= patient.discharge %></td>
		<td id='discharge-command-<%=patient.id %>'>
		<% if patient.discharge %>
		<%= link_to 'Decrement', decrement_patient_path(patient),:method=>:post,:remote=>true %>
		<% else %>
		<%= link_to 'Discharge', discharge_patient_path(patient,:claim_id=>@claims[patient.ward.hospital.id]),:method=>:post,:remote=>true %>
		<% end %>
		</td>

  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Patient', new_patient_path %>
<%= link_to 'Show All Hospital', rounds_path if Hospital.count>1 %>