config/routes.rb
Wardround::Application.routes.draw do
  
 
  
  
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  

  root :to => "rounds#index"
  
  resources :claims
  
  resources :reports

  resources :rounds do
      member do
        get 'return'
      end
    end

  resources :visits do
      collection do
        post 'remove'
        post 'charge'
        post 'uncharge'
      end
    end

  resources :patients  do
      member do
        post 'discharge'
        post 'undischarge'
        post 'decrement'
        post 'changeward'
        post 'changestatus'
        post 'under'
        post 'transfer'
        get 'report'
      end
    end
  
  resources :hospitals do
    collection do
      get 'wards_by_hospital'

    end
    member do
      get 'report'
      get 'handover'
      get 'change_hospital'
    end
  end
  
  resources :wards
  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  
  belongs_to :ward
  has_many :visits

  
  def visit(round)
    @visit=Visit.where(["patient_id=? and round_id=?",self.id,round]).first
  end
  
  def visited?(round)
    Visit.where(["patient_id=? and round_id=?",self.id,round]).present?
  end
  
  def charged?(round)
    Visit.where(["patient_id=? and round_id=? and item>0",self.id,round]).present?
  end
  
  def charge_icon(round)
    icon="";
    if Visit.where(["patient_id=? and round_id=? and item>0",self.id,round]).present?
      icon="c";
    end
    return icon
  end
  
  def under_icon
    icon=""
    if self.under==1
      icon="u"
    end
    return icon
  end
  
  def icons(round)
    icon="";
    if Visit.where(["patient_id=? and round_id=? and item>0",self.id,round]).present?
      icon+="c";
    end
    if self.under==1
      icon+="u"
    end
    @round=Round.find(round)
    if self.discharge == @round.date
      icon+="d"
    end
    return icon
  end
  
  def status_text
      r="Unknown"
      r="Public" if self.status==1
      r="Private" if self.status==2
      r="DVA" if self.status==3
      r="Workcover" if self.status==4
      return r
  end

  def item(round)
    charge=0
    @visit=Visit.where(["patient_id=? and round_id=?",self.id,round]).first
    if @visit
      charge=@visit.item
    end
    return charge
  end
  
  def otherHospitals
      Hospital.where(["id!=? ",self.ward.hospital.id])
  end
  

  

  def self.inThisMonth(month,year)
      Patient.where(["admission>?",Date.parse(year.to_s+"-"+month.to_s+"-01").strftime("%Y-%m-%d")])
  end
  
  def self.inHospitalThisPeriod(hospital,theDate=Date.today,period="month")
      @wards=Ward.where(["hospital_id=?",hospital])
      wardStr="("
      @wards.each do |ward|
        wardStr=wardStr+"ward_id="+ward.id.to_s+" or "
      end
      wardStr=wardStr+ "ward_id=0)"
      firstDay=theDate.at_beginning_of_month
      if period=='week'
        firstDay=theDate.at_beginning_of_week
      end
      lastDay=theDate.at_end_of_month
      if period=='week'
        lastDay=theDate.at_end_of_week
      end
      #Patient.find(:all,:conditions=>["admission>? and ?",Date.parse(year.to_s+"-"+month.to_s+"-01").strftime("%Y-%m-%d"),wardStr])
      Patient.where(["admission< ? and (discharge='' or discharge >= ?) and #{wardStr}",firstDay.strftime("%Y-%m-%d"),lastDay.strftime("%Y-%m-%d")])
      #Patient.find(:all,:conditions=>[wardStr])
  end

  # How many visits this period, how many charged
  
  def visitsBilled
      count=Visit.where(["patient_id=? and billed =?",self.id,true]).count
      return count
  end

  def visitsTotal
      count=Visit.where(["patient_id=?",self.id]).count
      return count
  end

  def visitsCharged
      count=Visit.where(["patient_id=? and item>0",self.id]).count
      return count
  end


  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  # default display
  # shows all current inpatients
  # GET /patients
  # GET /patients.json
  def index
    if params[:round_id] and params[:round_id]!='0'
      @round=Round.find(params[:round_id])
    else
        date=Date.today
        date=params[:date] if params[:date]
        order="DESC"
        order = params[:order] if params[:order]
        @round=Round.ondate(date,order)
    end
    @patients = Patient.inpatients(@round.date)
    #@patients=Patient.find(:all)
    @hospitals=Hospital.find(:all)
    @claims=Array.new
    @hospitals.each do |hospital|
      @claims[hospital.id]=Claim.find_or_create_by_round_id_and_hospital_id(:round_id=>@round.id,:hospital_id=> hospital.id)
    end
    @wards=Array.new
    @hospitals.each do |hospital|
      @wards[hospital.id]=Ward.where('hospital_id=?',hospital.id)
    end
   


    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])
    # best_in_place placeholder is unreliable
    #if @patient.reason=="" or @patient.reason== nil
     # @patient.reason="---"
    #end
    #if @patient.note=="" or @patient.note== nil
    #  @patient.note="---"
    #end
    if @patient.mrn=="" or @patient.mrn== nil
      @patient.mrn="---"
    end
    if params[:theDate]
        @theDate=Date.strptime(params[:theDate],'%d/%m/%y')
    end
    @return=params[:return]
    @handover=false
    if params[:handover]
      @handover=params[:handover]
    end


    @round_id=0
    if params[:round_id] and params[:round_id]!='0'
      @round=Round.find(params[:round_id])
      @round_id=@round.id
    end
    
    if params[:method]=="delete"
        @patient.destroy
        if @theDate
            redirect_to hospitals_path("theDate"=>@theDate) and return
        else
            redirect_to rounds_path(:id=>@round.id) and return
        end
      
    end
    if request.xhr?
      request.format = "mobile"
    end
    respond_to do |format|
      format.html 
      format.json { render :json => @patient }
      format.mobile 
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new
    @hospitals=Hospital.all
    @hospital=Hospital.first
    if params[:hospital_id]
      @hospital=Hospital.find(params[:hospital_id])
    end
    @patient.admission=Date.today
    if params[:round_id]
      @round=Round.find(params[:round_id])
      @patient.admission=@round.date
    end
    @wards = Hospital.find(@hospital.id).wards

    if request.xhr?
      request.format = "mobile"
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @hospitals=Hospital.find(:all)
    hospital=@hospitals[0]
    @wards = Hospital.find(hospital.id).wards
    @patient = Patient.find(params[:id])
    if params[:round_id]
      @round=Round.find(params[:round_id])
    end
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])
    if request.xhr?
      request.format = "mobile"
    end
    respond_to do |format|
      if @patient.save
        format.mobile { 
          if(params[:round_id])
            redirect_to rounds_path(:id=>params[:round_id])
          else
            redirect_to rounds_path
          end
        }
        format.html { redirect_to @patient, :notice => 'Patient was successfully created.' }
        format.json { render :json => @patient, :status => :created, :location => @patient }
      else
        format.html { render :action => "new" }
        format.json { render :json => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])
    params[:patient][:admission]=Date.strptime(params[:patient][:admission],'%d/%m/%Y') if params[:patient][:admission]
    params[:patient][:discharge]=Date.strptime(params[:patient][:discharge],'%d/%m/%Y') if params[:patient][:discharge]
    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, :notice => 'Patient was successfully updated.' }
        format.json { respond_with_bip(@patient) }
        format.js {render :nothing => true}
      else
        format.html { render :action => "edit" }
        format.json { render :json => @patient.errors, :status => :unprocessable_entity }
        format.js {render :nothing => true}
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { if @theDate
                      render :controller=> "hospitals/show"
                    end
                  }
      format.json { head :no_content }
    end
  end
  
  def discharge
      date=Date.today
      # source='patients/dischargepatient'
      # if params[:claim_id].present?
      #  @claim=Claim.find(params[:claim_id])
     #  date=@claim.date
      #  source='patients/discharge'
      # end
      @patient=Patient.update(params[:id],:discharge=>date)
      respond_to do |format|
        format.html
        format.js
      end
  end
  
  def transfer
      @patient = Patient.find(params[:id])

      @round= Round.find(params[:round])
      @newHospital=Hospital.find(params[:hospital])
      @patient=Patient.update(params[:id],:discharge=>params[:transfer_date])
      @patient.note=@patient.note+"\rTransferred to "+ @newHospital.name
      @patient=Patient.update(params[:id],:note=>@patient.note)

      
      @newPatient=Patient.new
      # dup doesn't work in Rail 3.2.5
      
      @newPatient.name=@patient.name
      @newPatient.note=@patient.note+"\rTransferred from "+ @patient.ward.hospital.name
      @newPatient.reason=@patient.reason
      @newPatient.under=@patient.under
      @newPatient.status=@patient.status
      @newPatient.charge=@patient.charge
      @newPatient.mrn=nil
      # @patient.note=@patient.note+"\rTransferred to "+ @newHospital.name
      
      
      @newPatient.admission=params[:transfer_date]
      @newPatient.ward_id=params[:ward_id]
      @newPatient.discharge=nil
      
      # @patient.update_attributes(params[:patient])
      @newPatient.save
      if request.xhr?
          request.format = "mobile"
      end
      
      respond_to do |format|
        format.html { redirect_to @newPatient, :notice => 'Patient was successfully transferred.' }
        format.mobile { redirect_to @round, :notice => 'Patient was successfully transferred.' }
        format.js
      end
      

  end
  
  def undischarge
    
      @patient=Patient.update(params[:id],:discharge=>'')
      respond_to do |format|
        format.html
        format.js {render :template => 'patients/undischarge.js'}
      end
  end
  def decrement
      @patient = Patient.find(params[:id])
      @patient.update_attribute(:discharge,@patient.discharge-1.day)
      respond_to do |format|
        format.html
        format.js
      end
  end
  
  def changeward
      @patient = Patient.find(params[:id])
      @patient.update_attribute(:ward_id,params[:ward_id])
      respond_to do |format|
        format.html
        format.js {render :nothing => true}
      end
      
  end
  
  def changestatus
      @patient = Patient.find(params[:id])
      @patient.update_attribute(:status,params[:status])
      respond_to do |format|
        format.html
        format.js {render :nothing => true}
        format.mobile
      end
      
  end
  
  def under
    @patient = Patient.find(params[:id])
    if @patient.under==0 or @patient.under==""
      @patient.under=1
    else
      @patient.under=0
    end
    @patient.update_attribute(:under,@patient.under)
    respond_to do |format|
      format.html
      format.js {render :nothing => true}
    end
  end
  
  def charge
    @patient = Patient.find(params[:id])

    @patient.charge=params[:charge]

    @patient.update_attribute(:charge,@patient.charge)
    respond_to do |format|
      format.html
      format.js {render :nothing => true}
    end
  end
  
  def uncharge
    @patient = Patient.find(params[:id])

    @patient.charge=params[:charge]

    @patient.update_attribute(:charge,@patient.charge)
    respond_to do |format|
      format.html
      format.js {render :nothing => true}
    end
  end

  def report
      @patient=set_patient
      @visits=Visit.where('patient_id=? and item>0',@patient.id).order(:date)
      @return= params[:return]
      request.format = "mobile"
      respond_to do |format|
        format.html 
        format.json { render :json => @patient }
        format.mobile 
      end
  end

  private
      # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:admission, :discharge, :name, :ward_id, :reason, :note, :mrn, :status, :under, :charge)
    end
  


end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/dischargeOld.js.erb
$('#discharge-<%=@patient.id%>').html("<%=@patient.discharge%>");
$('#discharge-command-<%=@patient.id%>').html("<%= escape_javascript(link_to 'Decrement', decrement_patient_path(@patient),:method=>:post,:remote=>true)%>");

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1><%=@round.date.strftime("%A %d-%m-%Y")  %> <%= @round.number.ordinalize+' visit' %></h1>
<%= link_to 'New visit on same day', return_round_path(@round) %><p>
<%= link_to 'Previous', patients_path(:date=>@round.date-1.day,:round_id=>@round.previous) %>

<%= link_to 'Next', patients_path(:date=>@round.date+1.day,:round_id=>@round.next,:order=>'ASC') unless @round.date==Date.today and @round.number==@round.visits%><p>

<table>

<% current_hospital=0 %>
<% @patients.each do |patient| %>

	<% if patient.ward.hospital.id!=current_hospital%>
	<tr><td colspan=2 valigh='top'><b><%= patient.ward.hospital.name%></b></td>
<td valign='middle'>
	<% if patient.ward.hospital.showtime %>
								<a href="#" onclick="$('#claim-<%=patient.ward.hospital.id%>').toggle('slow');return false;" style="text-decoration: none">Time</a>
								<% end %>
								</td>
	<td colspan=5>
			<%= render :partial => "claim", :object => @claims[patient.ward.hospital.id] if patient.ward.hospital.showtime%>
			</td>
			
		</tr>
	<% end%>
	<% current_hospital=patient.ward.hospital.id%>
  <tr>
		<td>

			<%= check_box_tag @claims[patient.ward.hospital.id].id,patient.id,patient.visited?(@claims[patient.ward.hospital.id].id),:class => 'patient-visit' %>

			</td>
    <td>
<span <%= "style='font-weight: bold'" if @patient.under==1%>><%= patient.name %></span></td>
    <td>
	<%= collection_select("ward",:id, @wards[current_hospital], :id, :name, {:selected => patient.ward.id}, {:class=>'ward-select',:name=>patient.id}) %>
	</td>

    <td><%= patient.admission %></td>
    <td id='discharge-<%=patient.id %>'><%= patient.discharge %></td>
		<td id='discharge-command-<%=patient.id %>'>
		<% if patient.discharge %>
		<%= link_to 'Decrement', decrement_patient_path(patient),:method=>:post,:remote=>true %>
		<% else %>
		<%= link_to 'Discharge', discharge_patient_path(patient,:claim_id=>@claims[patient.ward.hospital.id]),:method=>:post,:remote=>true %>
		<% end %>
		</td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/show.mobile.erb
<div data-role="page" data-theme="b" id='showpatient'  style='max-width: 600px;'> 
	     <div data-role="header">

		 <%= link_to 'Back', round_path(@round,:flag=>1),'data-transition'=>'slide','data-icon'=>'back','data-direction'=>'reverse' if @round %>
		 <%= link_to 'Back', hospitals_path(:theDate=>@theDate,:handover=>@handover),'data-icon'=>'back' if @return=="handover" %>
		<%= link_to 'Back',report_patient_path(@patient),'data-transition'=>'slide','data-icon'=>'back','data-direction'=>'reverse' if @return=="report"%>
		<%= link_to "Home",rounds_path(),"data-role"=>"button","data-icon"=>"home","data-inline"=>"true","data-iconpos"=>"notext","data-theme"=>"b",'data-transition'=>'slide','data-direction'=>'reverse'%>
	           <h1><%= @patient.name%></h1>
	     </div> 
	     <div data-role="content">
				<div data-role="fieldcontain">
				  <label><b>Name:  </b></label>
				  <%= best_in_place @patient, :name, :type => :input %>
				</div>
				<div data-role="fieldcontain">
				  <label><b>MRN:  </b></label>
				  <%= best_in_place @patient, :mrn,:type => :input,:ok_button => 'Save',:place_holder => "---Add",:cancel_button => 'Cancel'  %>
				</div>
				
					<div data-role="fieldcontain">
		      <label for="patient_ward_id">Ward:</label>
						<%= select(:patient, :ward_id,@patient.ward.hospital.wards.map {|x| [x.name, x.id] },{},{"data-native-menu"=>"false","data-mini"=>"true","data-patient"=>@patient.id}) %> 

					</div>
					<div data-role="fieldcontain">
					<b>Reason:</b>
				  <%= best_in_place @patient, :reason, :type => :input,:ok_button => 'Save',:place_holder => "---Add",:cancel_button => 'Cancel' %> 	 
					</div>

					<div data-role="fieldcontain">
					<b>Note:</b>
				  <%= best_in_place @patient, :note, :type => :input,:ok_button => 'Save',:place_holder => "---Add",:cancel_button => 'Cancel' %> 	 
				  </div>				
				
				
					<div data-role="fieldcontain">
					<label for="patient_admission">Admission      </label>

					<input name="patient[admission]" class='attrchanger' data-attr='patient[admission]' data-patient='<%=@patient.id %>' type="date" data-role="datebox"
					   data-options='{"mode": "calbox", "overrideDateFormat": "%-d/%m/%Y","defaultValue": <%= initalformatdate(@patient.admission) %>, "showInitialValue": true , "useFocus":true,"calControlGroup":true}'>

					</div>


					<div data-role="fieldcontain">
						<div id="discharge-<%=@patient.id%>" <%="style='display: none'".html_safe unless @patient.discharge%> >

							<label for="patient_discharge">Discharge      </label>
							<span id='picker-discharge-<%=@patient.id%>>'>

								<input name="patient[discharge]" class='attrchanger' data-attr='patient[discharge]' data-patient='<%=@patient.id %>' type="date" data-role="datebox"
								   data-options='{"mode": "calbox", "overrideDateFormat": "%-d/%m/%Y","defaultValue": <%= initalformatdate(@patient.discharge) %>, "showInitialValue": true,"useFocus":true,"calControlGroup":true}'>

							<div id='undischarge_button'<%="style='display: none'".html_safe unless @patient.discharge%> >
							 <button id='undischarge' data-mini='true' data-patient='<%=@patient.id%>'>UnDischarge</button>
							</div>
							</span>
							</div> 



						<div id='discharge_button' <%="style='display: none'".html_safe if @patient.discharge%>>
							<button id='discharge' data-mini='true' data-patient='<%=@patient.id%>'>Discharge</button>
						</div>
					</div>

					
				
				<% if @patient.otherHospitals.count >0 and @round %>
					<div data-role="fieldcontain">		
							<div id='transfer_button'>


								<a href="#transferConfirm" data-rel="popup" data-mini='true' data-role="button" data-transition="pop">Transfer</a>
							</div>
							<div data-role="popup" id="transferConfirm" data-overlay-theme="a" data-theme="c" class="ui-corner-all">
								<a href="#" data-rel="back" data-role="button" data-theme="a" data-icon="delete" data-iconpos="notext" class="ui-btn-right">Close</a>
							            <div data-role="header" data-theme="b" class="ui-corner-top">
							                <h1>Transfer</h1>
							            </div>
										
							            <div data-role="content" data-theme="b"class="ui-corner-bottom ui-content">
										<%= form_tag transfer_patient_path(@patient) do %>

											<input type='hidden' name='round' value='<%= @round.id %>'>
							                <h3 class="ui-title">Transfer to another hospital</h3>
							               
											<input name="transfer_date" class='attrchanger' data-attr='patient[transfer]' data-patient='<%=@patient.id %>' type="date" data-role="datebox"
											   data-options='{"mode": "calbox", "overrideDateFormat": "%-d/%m/%Y","defaultValue": <%= initalformatdate(@round.date ) %>, "showInitialValue": true,"zindex":10000,"useFocus":true,"calControlGroup":true}'>
											<div data-role="fieldcontain">
												
											  <%= select_tag("hospital",options_from_collection_for_select(@patient.otherHospitals,"id","name"),{"data-native-menu"=>"false","data-mini"=>"true","data-patient"=>@patient.id}) %> 
											
									
											</div>
											<div data-role="fieldcontain">
											 	
											  <%= select_tag("ward_id",options_from_collection_for_select(@patient.otherHospitals[0].wards,"id","name"),{"data-native-menu"=>"false","data-mini"=>"true","data-patient"=>@patient.id}) %> 
											</div>
							 	             <%= submit_tag "Transfer", {"data-native-menu"=>"false","data-mini"=>"true","data-patient"=>@patient.id} %>
											  
										<% end %>
										</div>
							</div>
					</div>
				<% end %>	
					
					
					
					
					
					
					
					
					
					
					
					<div data-role="fieldcontain">
					    <fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">
					    <legend>Status:</legend>
					<%= radio_button "patient","status","0",{'class'=>'attrchanger','data-attr'=>'patient[status]','data-patient'=>@patient.id} %>
					<label for="patient_status_0">--</label>
					<%= radio_button "patient","status", "1",{'class'=>'attrchanger','data-attr'=>'patient[status]','data-patient'=>@patient.id} %>
					<label for="patient_status_1">Pub</label>
					<%= radio_button "patient","status", "2",{'class'=>'attrchanger','data-attr'=>'patient[status]','data-patient'=>@patient.id} %>
					<label for="patient_status_2">Pte</label>
					<%= radio_button "patient","status", "3" ,{'class'=>'attrchanger','data-attr'=>'patient[status]','data-patient'=>@patient.id}%>
					<label for="patient_status_3">DVA</label>
					<%= radio_button "patient","status", "4" ,{'class'=>'attrchanger','data-attr'=>'patient[status]','data-patient'=>@patient.id}%>
					<label for="patient_status_4">WC</label>
					    </fieldset>
					</div>
<fieldset class="ui-grid-a">
<div class="ui-block-a" >
					<div data-role="fieldcontain">
					<label for="patient_under">Under Us</label>
					<%= select(:patient, :under, [["no",0],["yes",1]],{},{"data-role"=>"slider","data-mini"=>"true","class"=>"attrchanger","data-attr"=>"patient[under]","data-patient"=>@patient.id}) %>

					</div>
 </div>
<div class="ui-block-b" >
					<div data-role="fieldcontain">
					<label for="patient_charge">Charge Default</label>

					<%= select(:patient, :charge, [["no",0],["yes",1]],{},{"data-role"=>"slider","data-mini"=>"true","class"=>"attrchanger","data-attr"=>"patient[charge]","data-patient"=>@patient.id}) %>
					</div>

</div>
</fieldset>





					<% if @round %>
					<fieldset class="ui-grid-a">
 
					<div class="ui-block-a">
						<div data-role="fieldcontain">
						<label for='<%= @round.id %>'>Visit This Round (<%= @round.date %> )</label>

						<%= check_box_tag @round.id,@patient.id,@patient.visited?(@round.id),"data-mini"=>"true","data-inline"=>"true" %>
						</div>
					</div>
					<div class="ui-block-b" style='text-align: center'>
						<div data-role="fieldcontain" id="visititems" <%="style='display: none'".html_safe unless @patient.visited?(@round.id)%> >
						<% @visit=@patient.visit(@round.id) %>
					   
					    <fieldset data-role="controlgroup" data-type="horizontal" data-mini="true">

						<%= radio_button "visit","item","0",{'class'=>'visititemclass','data-attr'=>'visit[item]','data-round'=>@round.id,'data-patient'=>@patient.id} %>
						<label for="visit_item_0">No Charge</label>
						<%= radio_button "visit","item","1",{'class'=>'visititemclass','data-attr'=>'visit[item]','data-round'=>@round.id,'data-patient'=>@patient.id} %>
						<label for="visit_item_1">Normal</label>
						<%= radio_button "visit","item","2",{'class'=>'visititemclass','data-attr'=>'visit[item]','data-round'=>@round.id,'data-patient'=>@patient.id} %>
						<label for="visit_item_2">Long</label>
						</fieldset>
						</div>
					</div>
						<div data-role="fieldcontain" id="chargenote" <%="style='display: none'".html_safe unless @patient.visited?(@round.id)%> >
						<b>Charge Note:</b>
						<span id='chargenoteplace'>
						
						<% if @patient.visited?(@round.id)%>
						
				  <%= best_in_place @visit, :chargenote, :type => :input,:ok_button => 'Save',:place_holder => "---Add",:cancel_button => 'Cancel' %> 
				  		
				  	<% end %>
				  		</span>
						</div>
					</fieldset>

					<% end %>




				<div data-role="fieldcontain">
					
					
					
					
					 <%= link_to 'Done', round_path(@round,:flag=>1),'data-transition'=>'slide',"data-role"=>"button",'data-icon'=>'back','data-direction'=>'reverse' if @round %>
					 <%= link_to 'Done', hospitals_path(:theDate=>@theDate,:handover=>@handover),"data-role"=>"button",'data-icon'=>'back' if @return=="handover" %>
					<%= link_to 'Done',report_patient_path(@patient),'data-transition'=>'slide',"data-role"=>"button",'data-icon'=>'back','data-direction'=>'reverse' if @return=="report"%>

				</div>
				<div data-role="fieldcontain">		
						<div id='delete_button'>


							<a href="#deleteConfirm" style="background: red" data-rel="popup" data-role="button" data-icon="delete" data-transition="pop">Delete</a>
						</div>
						<div data-role="popup" id="deleteConfirm" data-overlay-theme="a" data-theme="c" class="ui-corner-all">
						            <div data-role="header" data-theme="b" class="ui-corner-top">
						                <h1>Delete Page?</h1>
						            </div>
						            <div data-role="content" data-theme="b"class="ui-corner-bottom ui-content">
						                <h3 class="ui-title">Are you sure you want to delete this patient?</h3>
						                <p> All data for this patient will be lost.This action cannot be undone.</p>
						                <a href="#" data-role="button" data-rel="back" data-theme="c" >Cancel</a> 
										<%= link_to "Delete",patient_path(@patient,"method"=>"delete","theDate"=>@theDate,"round_id"=>@round_id),'data-role'=>'button','data-icon'=>"delete","style"=>"background: red"%>  

									</div>
						</div>
				</div>



	     </div> 
<%= render partial: "shared/footer" %>
</div>