config/routes.rb
Wardround::Application.routes.draw do
  
 
  
  
  resources :users
  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
  

  root :to => "rounds#index"
  
  resources :claims
  
  resources :reports

  resources :rounds do
      member do
        get 'return'
      end
    end

  resources :visits do
      collection do
        post 'remove'
        post 'charge'
        post 'uncharge'
      end
    end

  resources :patients  do
      member do
        post 'discharge'
        post 'undischarge'
        post 'decrement'
        post 'changeward'
        post 'changestatus'
        post 'under'
        post 'transfer'
        get 'report'
      end
    end
  
  resources :hospitals do
    collection do
      get 'wards_by_hospital'

    end
    member do
      get 'report'
      get 'handover'
      get 'change_hospital'
    end
  end
  
  resources :wards
  

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

  has_many :wards
  has_many :rounds
  has_many :claims
  
  def inpatients(theDate=Date.today)
     @inpatients = Patient.joins(:ward => :hospital).where("hospital_id=?",self.id).where(["admission <=? and (discharge is NULL or discharge>=?)",theDate,theDate])

  end
  
  def patients(startDate,endDate)
     # @patients= Patient.inHospitalThisMonth(self.id,@month,@year)

       #Patient.find(:all,:conditions=>["admission>? and ?",Date.parse(year.to_s+"-"+month.to_s+"-01").strftime("%Y-%m-%d"),wardStr])
      @patients = Patient.joins(:ward => :hospital).where("hospital_id=?",self.id).where(["admission<= ? and (discharge is NULL or discharge >= ?)",endDate.strftime("%Y-%m-%d"),startDate.strftime("%Y-%m-%d")])
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController




  # GET /hospitals
  # GET /hospitals.json
  
 

  def index
    @hospitals = Hospital.all

    # get date - use current month as default
    if params[:theDate]
      @theDate=Date.strptime(params[:theDate],'%d/%m/%y')
    else
      @theDate= Date.today
    end
    
    if params[:handover] and params[:handover]!="false"
      @period='day'
      @startDate=@theDate
      @endDate=@theDate
      @prevDate=@theDate-1.day
      @nextDate=@theDate+1.day
      @periodSpan=1
      @handover=true;
      
    else
      @handover=false;
    
      if request_device?(:iphone)
        @period='week'
        @device='iphone'
        @startDate=@theDate.at_beginning_of_week
        @endDate=@startDate.at_end_of_week
        @prevDate=@startDate-1.week
        @nextDate=@startDate+1.week
        @periodSpan=7
        
      elsif request_device?(:ipad)
        @period='fortnight'
        @device='ipad'
        @startDate=@theDate.at_beginning_of_week
        @endDate=(@startDate+1.week).at_end_of_week
        @prevDate=@startDate-2.weeks
        @nextDate=@startDate+2.weeks
        @periodSpan=14
      else
        @period='month'
        @startDate=@theDate.at_beginning_of_month
        @endDate=@theDate.at_end_of_month
        @prevDate=@theDate-1.month
        @nextDate=@theDate+1.month
        @periodSpan=@endDate.day
      end
    end
    if request.xhr?
      request.format = "mobile"
    end
   
    respond_to do |format|
      format.mobile
      format.html # index.html.erb
      format.json { render :json => @hospitals }
    end
  end

  # GET /hospitals/1
  # GET /hospitals/1.json
  def show
    @hospital = Hospital.find(params[:id])
    # get date - use current month as default
    if params[:theDate]
      @theDate=Date.strptime(params[:theDate],'%d/%m/%y')
    else
      @theDate= Date.today
    end

  
 
    # get patients who were in hospital during that month
    if request.xhr?
      request.format = "mobile"
    end

    respond_to do |format|
      format.mobile
      format.html # show.html.erb
      format.json { render :json => @hospital }
    end
  end

  # GET /hospitals/new
  # GET /hospitals/new.json
  def new
    @hospital = Hospital.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @hospital }
    end
  end

  # GET /hospitals/1/edit
  def edit
    @hospital = Hospital.find(params[:id])
  end

  # POST /hospitals
  # POST /hospitals.json
  def create
    @hospital = Hospital.new(params[:hospital])

    respond_to do |format|
      if @hospital.save
        # else need to create a default ward
        @ward=Ward.new(:name=>"--",:hospital_id=>@hospital.id)
        @ward.save
        format.html { redirect_to @hospital, :notice => 'Hospital was successfully created.' }
        format.json { render :json => @hospital, :status => :created, :location => @hospital }
      else
        format.html { render :action => "new" }
        format.json { render :json => @hospital.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /hospitals/1
  # PUT /hospitals/1.json
  def update
    @hospital = Hospital.find(params[:id])

    respond_to do |format|
      if @hospital.update_attributes(params[:hospital])
        format.mobile { redirect_to @hospital, :notice => 'Hospital was successfully updated.' }
        format.html { redirect_to @hospital, :notice => 'Hospital was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @hospital.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /hospitals/1
  # DELETE /hospitals/1.json
  def destroy
    @hospital = Hospital.find(params[:id])
    @hospital.destroy

    respond_to do |format|
      format.html { redirect_to hospitals_url }
      format.json { head :no_content }
    end
  end

  def change_hospital
      @hospital=set_hospital
      @wards = @hospital.wards
  end
  
  
  def wards_by_hospital
    @hospital=Hospital.find(params[:hospital_id])
    @name=@hospital.name
    if params[:hospital_id].present?
      @wards = Hospital.find(params[:hospital_id].to_i).wards
    else
      @wards = []
    end

    respond_to do |format|
      format.html 
      format.js
    end
  end
  
  def  report
    @hospital = Hospital.find(params[:id])
    # get date - use current month as default
    if params[:month]
      @month=params[:month]
    else
      @month= Date.today.month
    end
    if params[:year]
      @year = params[:year]
    else
      @year = Date.today.year
    end
  
    @theDate=Date.parse(@year.to_s+"-"+@month.to_s+"-01")
    # get patients who were in hospital during that month
    @patients=Patient.inHospitalThisMonth(params[:id],@month,@year)
  end
  
  def handover
    @hospitals = Hospital.all
      @theDate= Date.today



   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @hospitals }
    end
  end

  private
      # Use callbacks to share common setup or constraints between actions.
    def set_hospital
      @hospital = Hospital.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hospital_params
      params.require(:hospital).permit(:name, :showtime, :duration, :item)
    end


  
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<%= form_for(@hospital) do |f| %>
  <% if @hospital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hospital.errors.count, "error") %> prohibited this hospital from being saved:</h2>

      <ul>
      <% @hospital.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :showtime %><br />
    <%= f.check_box :showtime,{}, true, false %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :item %><br />
    <%= f.text_field :item %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hospitals/_hospital.html.erb
<tr>
<td colspan=5>
<b><%= hospital.name %></b>
</td>
<% if periodSpan>1 %>

<% thisDate = startDate%>
<% for i in 1..periodSpan %>
	
	<td><%= thisDate.strftime("%a")%></td>
	<% thisDate= thisDate+1.day %>

<% end %>
<% end %>
</tr>


		<tr>
			<td>Patient</td>
		
			<td>Ward</td>
			<td>Admitted</td>
			<% if periodSpan==1 %>
				<td>Under Us</td>
				<td>Reason</td>
				<td>Note</td>
			<% else %>
				<td>Discharged</td>
				<td>Bill</td>
				<% thisDate = startDate%>
				<% for i in 1..periodSpan %>
					
					<td><%= link_to thisDate.day,rounds_path(:date=>thisDate,:hospital_id=>hospital.id) %></td>
					<% thisDate= thisDate+1.day %>
				<% end %>
			<% end %>
		</tr>
	<% hospital.patients(startDate,endDate).each do |patient| %>
	<tr>
		<td><%= link_to patient.name,report_patient_path(patient) %></td>

		<td><%= patient.ward.name %></td>
		<td><%= patient.admission %></td>
		<% if periodSpan==1 %>
			<td><%= patient.under %></td>
			<td><%= patient.reason %></td>
			<td><%= patient.note %></td>
		<% else %>
			<td><%= patient.discharge %></td>
			<td <%= "style='font-weight:bold;'".html_safe if patient.visitsBilled<patient.visitsCharged %>><%= patient.visitsBilled %>/<%= patient.visitsCharged %></td>
			<% thisDate = startDate %>
			<% for i in 1..periodSpan %>
				<td <%="style='background:#5e87b0';".html_safe unless (patient.discharge==NIL or thisDate <= patient.discharge) and patient.admission<=thisDate %>><%= Visit.code(patient.id,thisDate) %></td>
				<% thisDate = thisDate+1.day %>
			<% end %>
		<% end %>
	</tr>
	<% end %>

<p>
	

app/views/hospitals/change_hospital.js.erb
$('#ward_id').html('<%= escape_javascript(options_from_collection_for_select(@wards,"id","name")) %>');
$( "#ward_id" ).selectmenu( "refresh" );

app/views/hospitals/edit.html.erb
<h1>Editing hospital</h1>

<%= render 'form' %>

<%= link_to 'Show', @hospital %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/index.html.erb
<%=@theDate.strftime("%B")+", "+@theDate.strftime("%Y")%>

<p>
<%= link_to " < "+(@theDate-1.month).strftime("%B"), hospitals_path(:month=>(@theDate-1.month).month,:year=>(@theDate-1.month).year) %>  <%= link_to (@theDate+1.month).strftime("%B")+" > ", hospitals_path(:month=>(@theDate+1.month).month,:year=>(@theDate+1.month).year) %>
<p>

	<table border=1>
	<%= render(:partial => "hospital",:collection=> @hospitals, :locals=>{theDate: @theDate,startDate: @startDate, periodSpan: @periodSpan, endDate: @endDate})%>
	</table>



<%= link_to 'New Hospital', new_hospital_path %>

app/views/hospitals/index.mobile.erb
<div data-role="page" data-theme="b" > 
	<div data-role="header">
<%= link_to "Handover", hospitals_path(:handover=>true),"data-inline"=>"true",'data-transition'=>'flip' unless @handover%> 
<%= link_to "Report", hospitals_path(:handover=>false),"data-inline"=>"true",'data-transition'=>'flip'if @handover%> 
<h1>
<%= link_to "Home",rounds_path(),"data-role"=>"button","data-icon"=>"home","data-inline"=>"true","data-iconpos"=>"notext","data-theme"=>"b",'data-transition'=>'slide','data-direction'=>'reverse'%>
<%= link_to "Prev", hospitals_path(:theDate=>@prevDate,:handover=>@handover),"data-role"=>"button","data-icon"=>"arrow-l","data-inline"=>"true","data-iconpos"=>"notext","data-theme"=>"b",'data-transition'=>'slide','data-direction'=>'reverse' %><%= @theDate.strftime("%d") if @periodSpan==1 %> <%=@theDate.strftime("%B")+", "+@theDate.strftime("%Y")%>
<%= link_to "Next", hospitals_path(:theDate=>@nextDate,:handover=>@handover),"data-role"=>"button",'data-transition'=>'slide',"data-icon"=>"arrow-r","data-inline"=>"true","data-iconpos"=>"notext","data-theme"=>"b" %></h1>

    </div>
<p>


<div data-role="content"> 
	<% if @periodSpan==1%>
	<h3>Inpatient summary</h3>
	<% end %>
<table border=1>
<%= render(:partial => "hospital",:collection=> @hospitals, :locals=>{theDate: @theDate,startDate: @startDate, periodSpan: @periodSpan, endDate: @endDate})%>
</table>
</div>
<%= render partial: "shared/footer" %>

</div>

app/views/hospitals/new.html.erb
<h1>New hospital</h1>

<%= render 'form' %>

<%= link_to 'Back', hospitals_path %>

app/views/hospitals/report.html.erb
Summary for <%= @hospital.name%>   <%=@theDate.strftime("%B")+", "+@theDate.strftime("%Y")%>

<p>
<%= link_to " < "+(@theDate-1.month).strftime("%B"), report_hospital_path(:month=>(@theDate-1.month).month,:year=>(@theDate-1.month).year) %>  <%= link_to (@theDate+1.month).strftime("%B")+" > ", report_hospital_path(:month=>(@theDate+1.month).month,:year=>(@theDate+1.month).year) %>
<table border=1>
	<tr>
		<td>Patient</td>
		<td>Admitted</td>
		<td>Discharged</td>
		<% for i in 1..Time.days_in_month(@month.to_i, @year.to_i) %>
			<td><%= i %></td>
		<% end %>
	</tr>
<% @patients.each do |patient| %>
<tr>
<td><%= patient.name %></td>
<td><%= patient.admission %></td>
<td><%= patient.discharge %></td>
<% for i in 1..Time.days_in_month(@month.to_i, @year.to_i) %>
	<td><%= Visit.code(patient.id,i,@month,@year) %></td>
<% end %>
</tr>
<% end %>
</table>

app/views/hospitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hospital.name %>
</p>
<p>
  <b>Duration:</b>
  <%= @hospital.duration %>
</p>
<p>
  <b>Item:</b>
  <%= @hospital.item %>
</p>
<p>
  <b>Showtime:</b>
  <%= @hospital.showtime %>
</p>


<%= link_to 'Edit', edit_hospital_path(@hospital) %> |
<%= link_to 'Back', hospitals_path %>

app/views/hospitals/wards_by_hospital.html.erb
Hospital Wards here<p>
<%= debug(params) %>
<%= debug(@hospital) %>

app/views/hospitals/wards_by_hospital.js.erb
$("#patient_ward_id").html("<%= escape_javascript(options_for_select(@wards.map {|sc| [sc.name, sc.id]})) %>");
$("#patient_ward_id").selectmenu('refresh', true);